name: Node

concurrency:
    group: Node-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write
    contents: write
    pull-requests: write

on:
    workflow_dispatch:
    push:
        branches: [Current]
    pull_request:
        branches: [Current]
    workflow_call:

jobs:
    Pre-Publish:
        runs-on: ubuntu-latest

        env:
            ADBLOCK: true
            ASTRO_TELEMETRY_DISABLED: 1
            AUTOMATEDLAB_TELEMETRY_OPTOUT: 1
            AZURE_CORE_COLLECT_TELEMETRY: 0
            CHOOSENIM_NO_ANALYTICS: 1
            DIEZ_DO_NOT_TRACK: 1
            DOTNET_CLI_TELEMETRY_OPTOUT: 1
            DOTNET_INTERACTIVE_CLI_TELEMETRY_OPTOUT: 1
            DO_NOT_TRACK: 1
            ET_NO_TELEMETRY: 1
            GATSBY_TELEMETRY_DISABLED: 1
            GATSBY_TELEMETRY_OPTOUT: 1
            GATSBY_TELEMETRY_OPT_OUT: 1
            GRIT_TELEMETRY_DISABLED: 1
            HASURA_GRAPHQL_ENABLE_TELEMETRY: false
            HINT_TELEMETRY: off
            HOMEBREW_NO_ANALYTICS: 1
            INFLUXD_REPORTING_DISABLED: true
            ITERATIVE_DO_NOT_TRACK: 1
            NEXT_TELEMETRY_DEBUG: 1
            NEXT_TELEMETRY_DISABLED: 1
            NG_CLI_ANALYTICS: false
            NUXT_TELEMETRY_DISABLED: 1
            PIN_DO_NOT_TRACK: 1
            POWERSHELL_TELEMETRY_OPTOUT: 1
            SAM_CLI_TELEMETRY: 0
            STNOUPGRADE: 1
            STRIPE_CLI_TELEMETRY_OPTOUT: 1
            TELEMETRY_DISABLED: 1
            TERRAFORM_TELEMETRY: 0

        strategy:
            matrix:
                node-version: [18, 19, 20]

        steps:
            - uses: actions/checkout@v4.1.7

            - uses: pnpm/action-setup@v4.0.0
              with:
                  version: 9.3.0
                  run_install: |
                      - recursive: true
                        args: [
                          --link-workspace-packages=true,
                          --lockfile-only,
                          --prefer-frozen-lockfile=false,
                          --shamefully-hoist=false,
                          --shared-workspace-lockfile=true,
                          --strict-peer-dependencies=false,
                          --unsafe-perm=true
                        ]

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./examples/docusaurus/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./examples/docusaurus

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-examples-docusaurus-Node-${{ matrix.node-version }}-Target
                  path: ./examples/docusaurus/Target

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./examples/vuepress-next/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./examples/vuepress-next

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./examples/vuepress/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./examples/vuepress

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./pnpm-lock.yaml

            - run: pnpm install
              working-directory: .

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-Node-${{ matrix.node-version }}-Target
                  path: ./Target

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/docusaurus-plugin-typedoc/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/docusaurus-plugin-typedoc

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-docusaurus-plugin-typedoc-Node-${{ matrix.node-version }}-Target
                  path: ./packages/docusaurus-plugin-typedoc/Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-docusaurus-plugin-typedoc-Node-${{ matrix.node-version }}-Target
                  path: ./packages/docusaurus-plugin-typedoc/Target

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/typedoc-bitbucket-theme/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/typedoc-bitbucket-theme

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-typedoc-bitbucket-theme-Node-${{ matrix.node-version }}-Target
                  path: ./packages/typedoc-bitbucket-theme/Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-typedoc-bitbucket-theme-Node-${{ matrix.node-version }}-Target
                  path: ./packages/typedoc-bitbucket-theme/Target

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/typedoc-github-wiki-theme/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/typedoc-github-wiki-theme

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-typedoc-github-wiki-theme-Node-${{ matrix.node-version }}-Target
                  path: ./packages/typedoc-github-wiki-theme/Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-typedoc-github-wiki-theme-Node-${{ matrix.node-version }}-Target
                  path: ./packages/typedoc-github-wiki-theme/Target

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/typedoc-gitlab-wiki-theme/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/typedoc-gitlab-wiki-theme

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-typedoc-gitlab-wiki-theme-Node-${{ matrix.node-version }}-Target
                  path: ./packages/typedoc-gitlab-wiki-theme/Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-typedoc-gitlab-wiki-theme-Node-${{ matrix.node-version }}-Target
                  path: ./packages/typedoc-gitlab-wiki-theme/Target

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/typedoc-hugo-theme/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/typedoc-hugo-theme

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-typedoc-hugo-theme-Node-${{ matrix.node-version }}-Target
                  path: ./packages/typedoc-hugo-theme/Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-typedoc-hugo-theme-Node-${{ matrix.node-version }}-Target
                  path: ./packages/typedoc-hugo-theme/Target

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-typedoc-plugin-markdown-Node-${{ matrix.node-version }}-Target
                  path: ./packages/typedoc-plugin-markdown/Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-typedoc-plugin-markdown-Node-${{ matrix.node-version }}-Target
                  path: ./packages/typedoc-plugin-markdown/Target

            - uses: actions/setup-node@v4.0.3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"
                  cache-dependency-path: ./packages/vuepress-plugin-typedoc/pnpm-lock.yaml

            - run: pnpm install
              working-directory: ./packages/vuepress-plugin-typedoc

            - run: pnpm run build
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-vuepress-plugin-typedoc-Node-${{ matrix.node-version }}-Target
                  path: ./packages/vuepress-plugin-typedoc/Target

            - run: pnpm run prepublishOnly
              working-directory: .

            - uses: actions/upload-artifact@v4.3.4
              with:
                  name: .-packages-vuepress-plugin-typedoc-Node-${{ matrix.node-version }}-Target
                  path: ./packages/vuepress-plugin-typedoc/Target
